# 1. UTILIZAR CONCEPTOS FUNDAMENTALES DE PYTHON PARA LA CONSTRUCCIÓN DE PROGRAMAS (VARIABLES/OPERADORES)
# 2. DISTINGUIR TIPOS DE DATOS Y SENTENCIAS BASICAS DEL LENGUAJE PARA LA CONSTRUCCIÓN DE PROGRAMAS (STRING/INT/FLOAT/BOOLEAN)
# 3. UTILIZAR SENTENCIAS CONDICIONALES PARA EL CONTROL  DE FLUJO DE UN ALGORITMO QUE RESUELVA UN PROBLEMA (IF/ELIF/ELSE)
# 4. UTILIZAR SENTENCIAS ITERATIVAS PARA LA ELABORACIÓN DE UN ALGORITMO QUE RESUELVA UN PROBLEMA (FOR/WHILE)
# 5. UTILIZAR ESTRUCTURAS DE DATOS PARA LA RESOLUCIÓN DE PROBLEMAS (LISTAS/TUPLAS/DICCIONARIOS)

# TIENDA DE REGALOS - DESCUENTO SOLO SI COMPRA 3 O MÁS PRODUCTOS Y ES SU CUMPLEAÑOS

print("\nBIENVENIDO A TU TIENDA DE REGALOS\n")
print("PARA OBTENER DESCUENTO DE CUMPLEAÑOS DEBES COMPRAR AL MENOS 3 PRODUCTOS.\n")

# VALIDAMOS CON WHILE QUE EL USUARIO RESPONDA SOLO "si" O "no"
respuesta = input("¿ES HOY TU CUMPLEAÑOS? (si/no): ").lower()
while respuesta != "si" and respuesta != "no":
    print("POR FAVOR RESPONDE SOLO CON 'si' O 'no'")
    respuesta = input("¿ES HOY TU CUMPLEAÑOS? (si/no): ").lower()

# CONVERTIMOS LA RESPUESTA EN UN BOOLEANO (TRUE SI ES "si", FALSE SI NO)
es_cumpleaños = respuesta == "si"

# PEDIMOS LA CANTIDAD DE PRODUCTOS QUE VA A COMPRAR
num_productos = int(input("\n¿CUÁNTOS PRODUCTOS VAS A COMPRAR?: "))
print()

# CREAMOS UNA LISTA VACÍA PARA GUARDAR LOS PRECIOS DE LOS PRODUCTOS
precios = []

# BUCLE FOR PARA PEDIR EL PRECIO DE CADA PRODUCTO
# range(num_productos) CREA UNA SECUENCIA DE NÚMEROS DE 0 A num_productos-1
# i ES EL CONTADOR AUTOMÁTICO QUE SE USA PARA MOSTRAR EL NÚMERO DEL PRODUCTO
for i in range(num_productos):
    precio = float(input(f"INGRESA EL PRECIO DEL PRODUCTO {i+1}: $ "))
    precios.append(precio)  # AGREGAMOS EL PRECIO A LA LISTA 'precios'

# PEDIMOS LA EDAD DEL CLIENTE
edad = int(input("\nINGRESA TU EDAD: "))

# SUMAMOS TODOS LOS PRECIOS DE LA LISTA USANDO sum()
total = sum(precios)

# USAMOS UNA ESTRUCTURA CONDICIONAL PARA DETERMINAR SI APLICA EL DESCUENTO
if es_cumpleaños and num_productos >= 3:
    descuento = total * edad / 100  # CALCULAMOS EL DESCUENTO COMO PORCENTAJE DE LA EDAD
    print("\n¡FELICIDADES! POR TU CUMPLEAÑOS Y TU COMPRA, TIENES DESCUENTO.")
else:
    descuento = 0  # SI NO CUMPLE LAS CONDICIONES, NO HAY DESCUENTO
    # MOSTRAMOS MENSAJES SEGÚN LA RAZÓN POR LA QUE NO TIENE DESCUENTO
    if not es_cumpleaños:
        print("\nHOY NO ES TU CUMPLEAÑOS, NO HAY DESCUENTO.")
    else:
        print("\nDEBES COMPRAR AL MENOS 3 PRODUCTOS PARA OBTENER DESCUENTO.")

# CALCULAMOS EL PRECIO FINAL RESTANDO EL DESCUENTO AL TOTAL
precio_final = total - descuento

# MOSTRAMOS EL RESUMEN FINAL FORMATEADO SIN DECIMALES
print(f"\nTOTAL DE LA COMPRA: $ {total:.0f}")
print(f"DESCUENTO APLICADO: $ {descuento:.0f}")
print(f"PRECIO FINAL A PAGAR: $ {precio_final:.0f}\n")


# 6. UTILIZAR FUNCIONES PARA LA RESOLUCIÓN DE PROBLEMAS (FUNCIONES/RETORNO)
