# 1. UTILIZAR CONCEPTOS FUNDAMENTALES DE PYTHON PARA LA CONSTRUCCIÓN DE PROGRAMAS (VARIABLES/OPERADORES)
# 2. DISTINGUIR TIPOS DE DATOS Y SENTENCIAS BASICAS DEL LENGUAJE PARA LA CONSTRUCCIÓN DE PROGRAMAS (STRING/INT/FLOAT/BOOLEAN)
# 3. UTILIZAR SENTENCIAS CONDICIONALES PARA EL CONTROL  DE FLUJO DE UN ALGORITMO QUE RESUELVA UN PROBLEMA (IF/ELIF/ELSE)
# 4. UTILIZAR SENTENCIAS ITERATIVAS PARA LA ELABORACIÓN DE UN ALGORITMO QUE RESUELVA UN PROBLEMA (FOR/WHILE)
# 5. UTILIZAR ESTRUCTURAS DE DATOS PARA LA RESOLUCIÓN DE PROBLEMAS (LISTAS/TUPLAS/DICCIONARIOS)
# TIENDA DE REGALOS - DESCUENTO SOLO SI COMPRA 3 O MÁS PRODUCTOS Y ES SU CUMPLEAÑOS


# IMPORTAMOS LA FUNCIÓN pedir_respuesta_cumple DESDE def_tienda.py
from def_portafolio import pedir_respuesta_cumple

# MENSAJE INICIAL
print("\nBIENVENIDO A TU TIENDA DE REGALOS\n")
print("PARA OBTENER DESCUENTO DE CUMPLEAÑOS DEBES COMPRAR AL MENOS 3 PRODUCTOS.\n")

# USAMOS LA FUNCIÓN IMPORTADA PARA SABER SI ES CUMPLEAÑOS
es_cumpleaños = pedir_respuesta_cumple()

# PEDIMOS LA CANTIDAD DE PRODUCTOS
num_productos = int(input("\n¿CUÁNTOS PRODUCTOS VAS A COMPRAR?: "))
print()

# LISTA PARA GUARDAR LOS PRECIOS
precios = []

# BUCLE FOR PARA PEDIR LOS PRECIOS DE CADA PRODUCTO
for i in range(num_productos):
    precio = float(input(f"INGRESA EL PRECIO DEL PRODUCTO {i+1}: $ "))
    precios.append(precio)

# PEDIMOS LA EDAD DEL CLIENTE
edad = int(input("\nINGRESA TU EDAD: "))

# CALCULAMOS EL TOTAL DE LA COMPRA
total = sum(precios)

# VERIFICAMOS SI SE APLICA EL DESCUENTO (CUMPLEAÑOS Y 3 PRODUCTOS)
if es_cumpleaños and num_productos >= 3:
    descuento = total * edad / 100
    print("\n¡FELICIDADES! POR TU CUMPLEAÑOS Y TU COMPRA, TIENES DESCUENTO.")
else:
    descuento = 0
    if not es_cumpleaños:
        print("\nHOY NO ES TU CUMPLEAÑOS, NO HAY DESCUENTO.")
    else:
        print("\nDEBES COMPRAR AL MENOS 3 PRODUCTOS PARA OBTENER DESCUENTO.")

# CALCULAMOS EL PRECIO FINAL
precio_final = total - descuento

# MOSTRAMOS EL RESULTADO FINAL
print(f"\nTOTAL DE LA COMPRA: $ {total:.0f}")
print(f"DESCUENTO APLICADO: $ {descuento:.0f}")
print(f"PRECIO FINAL A PAGAR: $ {precio_final:.0f}\n")
