# 1. UTILIZAR CONCEPTOS FUNDAMENTALES DE PYTHON PARA LA CONSTRUCCIÓN DE PROGRAMAS (VARIABLES/OPERADORES)
# 2. DISTINGUIR TIPOS DE DATOS Y SENTENCIAS BASICAS DEL LENGUAJE PARA LA CONSTRUCCIÓN DE PROGRAMAS (STRING/INT/FLOAT/BOOLEAN)
# 3. UTILIZAR SENTENCIAS CONDICIONALES PARA EL CONTROL  DE FLUJO DE UN ALGORITMO QUE RESUELVA UN PROBLEMA (IF/ELIF/ELSE)
# 4. UTILIZAR SENTENCIAS ITERATIVAS PARA LA ELABORACIÓN DE UN ALGORITMO QUE RESUELVA UN PROBLEMA (FOR/WHILE)
# 5. UTILIZAR ESTRUCTURAS DE DATOS PARA LA RESOLUCIÓN DE PROBLEMAS (LISTAS/TUPLAS/DICCIONARIOS)

# TIENDA DE REGALOS - DESCUENTO DE DÍA DE CUMPLEAÑOS SOLO SI COMPRA 3 O MÁS PRODUCTOS Y ES CUMPLEAÑOS

print("\nBIENVENIDO A TU TIENDA DE REGALOS\n")
print("Para obtener descuento de cumpleaños debes comprar al menos 3 productos.\n")

# PREGUNTAMOS SI ES CUMPLEAÑOS Y GUARDAMOS COMO BOOLEANO (TRUE SI RESPONDE "si", FALSE SI NO)
respuesta = input("¿ES HOY TU CUMPLEAÑOS? (si/no): ").lower()
es_cumpleaños = respuesta == "si"

# PREGUNTAMOS CUÁNTOS PRODUCTOS VA A COMPRAR
num_productos = int(input("¿CUÁNTOS PRODUCTOS VAS A COMPRAR?: "))
print()

# CREAMOS UNA LISTA VACÍA PARA GUARDAR LOS PRECIOS DE LOS PRODUCTOS
precios = []

# BUCLE FOR PARA PEDIR EL PRECIO DE CADA PRODUCTO
# range(num_productos) CREA UNA SECUENCIA DE NÚMEROS DESDE 0 HASTA num_productos-1
# i ES EL CONTADOR QUE CAMBIA EN CADA ITERACIÓN (0, 1, 2, ...)
# USAMOS f-string PARA MOSTRAR EL NÚMERO DEL PRODUCTO (i+1) EMPEZANDO EN 1 EN LUGAR DE 0
for i in range(num_productos):
    precio = float(input(f"INGRESA EL PRECIO DEL PRODUCTO {i+1}: $ "))
    # AGREGAMOS CADA PRECIO INGRESADO AL FINAL DE LA LISTA 'precios'
    precios.append(precio)

# PEDIMOS LA EDAD DEL CLIENTE (ENTERO)
edad = int(input("\nINGRESA TU EDAD: "))

# SUMAMOS TODOS LOS PRECIOS DE LA LISTA USANDO LA FUNCIÓN sum()
total = sum(precios)

# SENTENCIA IF PARA DECIDIR SI APLICAMOS EL DESCUENTO
# CONDICIÓN: SOLO HAY DESCUENTO SI ES CUMPLEAÑOS (es_cumpleaños ES TRUE)
# Y SI EL NÚMERO DE PRODUCTOS ES MAYOR O IGUAL A 3
if es_cumpleaños and num_productos >= 3:
    # CALCULAMOS EL DESCUENTO COMO EL PORCENTAJE DE LA EDAD
    descuento = total * edad / 100
    print("\n¡FELICIDADES! POR TU CUMPLEAÑOS Y TU COMPRA, TIENES DESCUENTO.")
else:
    descuento = 0  # SI NO SE CUMPLE LA CONDICIÓN, NO HAY DESCUENTO
    # SENTENCIA IF DENTRO DEL ELSE PARA DIFERENCIAR EL MOTIVO DEL NO DESCUENTO
    if not es_cumpleaños:
        print("\nHOY NO ES TU CUMPLEAÑOS, NO HAY DESCUENTO.")
    else:
        print("\nDEBES COMPRAR AL MENOS 3 PRODUCTOS PARA OBTENER DESCUENTO.")

# CALCULAMOS EL PRECIO FINAL RESTANDO EL DESCUENTO AL TOTAL
precio_final = total - descuento

# MOSTRAMOS LOS RESULTADOS FORMATOS CON 0 DECIMALES
print(f"\nTOTAL DE LA COMPRA: $ {total:.0f}")
print(f"DESCUENTO APLICADO: $ {descuento:.0f}")
print(f"PRECIO FINAL A PAGAR: $ {precio_final:.0f}\n")


# 6. UTILIZAR FUNCIONES PARA LA RESOLUCIÓN DE PROBLEMAS (FUNCIONES/RETORNO)
